### ISSUE TITLE
header files are missing the include guards

### ISSUE THREAD

**Issue by tfarina** [mgatny/quickfix_101#2]
It is better to guard header files by:

#ifndef FOO_H_
#define FOO_H_

....

#endif  // FOO_H_

than to use #pragma once.

References:
http://en.wikipedia.org/wiki/Include_guard
https://groups.google.com/a/chromium.org/d/topic/chromium-dev/RMcVNGjB4II/discussion

**Comment by mgatny** [comment]
closed by #3

**Comment by tfarina** [comment]
Thank you.
